### ISSUE TITLE
How to use bfj.parse on the Request .pipe method

### ISSUE THREAD

**Issue by tomgrossman** [philbooth/bfj#45]
Hi,
I was wondering how to implement the `parse` method on the http request pipe method.
since the response is a `readableStream` I understand I can use it on the `bfj.parse` method, but the `parse` method gets a parameter, I can't pipe the stream into it.

for example, I was expecting something like this:

```javascript
    const Request = require('request');

    Request({url: 'blabla.com'}).pipe(bfj.parse().then(
        (parseResult) => {
            // parseResult is the parsing result of the response stream
        }
    ));
```

but it's not possible because `parse` should get the stream as a parameter.
If I'm piping the `Request` result into a `writableStream`, I can't parse it because it is not readable.

Any ideas or solutions?

thanks!

**Comment by philbooth** [comment]
@tomgrossman as it stands, the easiest way to do this is with [`stream.PassThrough`](https://nodejs.org/api/stream.html#stream_class_stream_passthrough):

```js
const jsonstream = new stream.PassThrough()
request({ url: 'https://example.com/foo.json' }).pipe(jsonstream)
bfj.parse(jsonstream)
  .then(data => {
    // :)
  })
  .catch(err => {
    // :(
  })
```

But I'm also open to suggestions if there is a more conventional approach I should be supporting.

For instance, maybe I should add some method that returns a `WritableStream` so that it can be passed to `pipe` directly? Perhaps called `unpipe` or something? Thoughts?

**Comment by tomgrossman** [comment]
@philbooth but if you return a `WritableStream` you won't be able to use `parse` on it as it is not readable. Maybe `unpipe` should get also a callback function that it's value would be a `ReadableStream` after conversion from writable to readable so you can use `parse` on it.

Anyway, I will try the `stream.PassThrough` option and get back to you :)

**Comment by philbooth** [comment]
> but if you return a `WritableStream` you won't be able to use `parse` on it as it is not readable.

The writable stream would be for passing in to `pipe`, not to bfj. For instance, something like:

```js
request({ url }).pipe(bfj.unpipe((err, data) => {
  if (err) {
    // :(
  } else {
    // :)
  }
}))
```

Obviously, it's not very promisey in that form, which doesn't match the rest of the library very well. Having a think about other ways to express it now...

**Comment by tomgrossman** [comment]
Well, it seems like I'm getting memory exception when using `parse` on a large JSON.

The code on the api server side, which I think is working fine is as follows:
```javascript
return new Promise(function (Resolve, Reject) {
    bfj.streamify(OrigJson).on('error', (error) => {
        return Reject(error);
    }).pipe(DestWritableStream);

    DestWritableStream.on('error', (error) => {
        return Reject(error);
    }).on('finish', () => {
        return Resolve(true);
    });
});
```
on the receiver side, the code is as follows:
```javascript
return new Promise(function (Resolve, Reject) {
    let jsonstream = new stream.PassThrough();

    Request({url: 'blabla.com'}).on('error', (error) => {
        return Reject(error);
    }).pipe(jsonstream);

    bfj.parse(jsonstream).then(
        (ResultJson) => {
            return Resolve(ResultJson);
        }
    ).catch(
        (ErrorInst) => {
            return Reject(ErrorInst);
        }
    );
});
```
after sometime when the receiver CPU is on 100%, I'm getting the following exception:

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
>  1: node::Abort() [/usr/bin/node]
>  2: 0x10d2fbc [/usr/bin/node]
>  3: 
> <--- Last few GCs --->
> 
>   318425 ms: Mark-sweep 1373.8 (1434.9) -> 1373.8 (1434.9) MB, 1372.4 / 0.0 ms [allocation failure] [GC in old space requested].
>   319867 ms: Mark-sweep 1373.8 (1434.9) -> 1375.1 (1404.9) MB, 1442.0 / 0.0 ms [last resort gc].
>   321296 ms: Mark-sweep 1375.1 (1404.9) -> 1376.4 (1404.9) MB, 1429.1 / 0.0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x3fe6bcfcfb39 <JS Object>
>     2: new Promise [native promise.js:53] [pc=0x1de4a5961dd9] (this=0x3fe6bcf04429 <the hole>,v=0x20abb8ba90f1 <JS Function Promise (SharedFunctionInfo 0x2fc3e5bd6e41)>)
>     4: awaitCharacter(aka awaitCharacter) [/home/tom/intsights/agent/dashboard_synchronizer/node_modules/bfj/src/walk.js:~104] [pc=0x1de4a5d3ea2e] (this=0x3fe6bcf04381 <undefined>)
>     5: wait(aka wait) [/home/tom/intsights/age...
> 
> v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
>  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
>  5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/usr/bin/node]
>  6: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) [/usr/bin/node]
>  7: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::MacroAssembler*, v8::internal::CompilationInfo*) [/usr/bin/node]
>  8: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [/usr/bin/node]
>  9: 0xb4d478 [/usr/bin/node]
> 10: 0xb4e788 [/usr/bin/node]
> 11: 0xb57661 [/usr/bin/node]
> 12: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/usr/bin/node]
> 13: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
> 14: 0x1de4a55092a7
> 
> Process finished with exit code 134 (interrupted by signal 6: SIGABRT) 
> 

When I'm using the `Request` with regular callback function (no `bfj` at all), the response is returned after few small seconds.
So I think in the meanwhile I will stay with `bfj` only on the api server side.

**Comment by philbooth** [comment]
Oh, that's interesting, I'm going to dig into memory usage now, pretty sure there are some things I can do to improve it. Also, some variation on #41 could be helpful for avoiding out-of-memory problems, depending on the use case.

Thanks for raising it!

**Comment by philbooth** [comment]
@tomgrossman, I've published a new version `3.0.0` that contains a [fix to try and avoid out-of-memory exceptions in `parse`](https://github.com/philbooth/bfj/commit/18da753c89c0debf14595394b866eb2ecdbc7871).

Essentially the fix works be pre-allocating an array up-front to store the data, rather than working with strings as I was doing before. This should also speed `parse` up a bit because it isn't dynamically growing and shrinking strings. You can control the size of the pre-allocated array using the new `size` and `grow` options, details in the readme.

I'd be interested to know if this fixes your out-of-memory exception or if you still see it. If you get a chance to try it out, please let me know!

Also, fwiw, as part of the same release I decided to add the `unpipe` method from my earlier comment in this thread, in case you're interested in using that too (it just does what you're already doing with `stream.PassThrough` under the hood).

**Comment by philbooth** [comment]
> I'd be interested to know if this fixes your out-of-memory exception or if you still see it.

On the assumption that no news is good news, I'm closing this. Feel free to re-open it if you still have an issue.

**Comment by tomgrossman** [comment]
Testing with `unpipe` function, I still get a memory exception:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
`

**Comment by philbooth** [comment]
Ah that's a shame, thanks for letting me know! I'll try and dig into it again some more soon.

**Comment by philbooth** [comment]
Hey @tomgrossman, I've made a few improvements to memory management in recent versions and it would be interesting to know if the problem you were having with `bfj.unpipe` still occurs in version `4.2.3`. If you have a bit of spare time to try it out and report back, that would be greatly appreciated!

**Comment by tomgrossman** [comment]
@philbooth It'll take a while until I'll have some spare time to check this. I think you should close this issue and in case someone or I will ever encounter it again, it can be reopened.
Thanks anyway for all the hard work!
